/*
 * Conformance checks over the vendored yEnc encryption standards v1.2 test
 * vector fixtures (tests/test-vectors/, byte-identical copies of the canonical
 * set generated by the reference standards repository and pinned by
 * manifest.json). Fixture-driven via QJsonDocument.
 *
 * Coverage: fixture integrity (manifest sha256 sync via
 * QCryptographicHash), VEC-05 malformed-input rejection shapes, VEC-06 NZB
 * meta tag expectations, and VEC-07 segmentIndex allocation skip rules.
 * Cryptographic round-trip vectors are exercised by CryptoTest.
 *
 * v1.2 note: encrypted NZBs carry exactly <meta type="yenc_encrypted">true</meta>
 * and <meta type="password">; ngPost's NzbWriter emits no other encryption meta
 * (there is deliberately no <meta type="encryption">combined</meta>).
 *
 * Self-containment: reads only files inside ngPost/'s own tree.
 */

#include <QByteArray>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QJsonValue>
#include <QtTest>

#include <QDir>
#include <QHash>

class ConformanceVectorsTest : public QObject
{
    Q_OBJECT

private:
    QByteArray readFixtureFile(const QString &fileName) const
    {
        // Primary: source-tree location baked in at qmake time so the binary
        // works from any build directory.
        QString path = QStringLiteral(TEST_VECTORS_DIR) + QLatin1Char('/') + fileName;
        QFile file(path);
        if (!file.open(QIODevice::ReadOnly))
        {
            // Fallback: vendored set copied next to the binary.
            path = QDir(QCoreApplication::applicationDirPath()).filePath(
                QStringLiteral("test-vectors") + QLatin1Char('/') + fileName);
            file.setFileName(path);
            if (!file.open(QIODevice::ReadOnly))
                qFatal("vendored fixture missing: %s", qPrintable(path));
        }
        return file.readAll();
    }

    QJsonObject loadFixture(const QString &fileName) const
    {
        const QByteArray raw = readFixtureFile(fileName);
        QJsonParseError parseError;
        const QJsonDocument doc = QJsonDocument::fromJson(raw, &parseError);
        if (parseError.error != QJsonParseError::NoError || !doc.isObject())
            qFatal("invalid JSON in fixture %s: %s", qPrintable(fileName), qPrintable(parseError.errorString()));
        return doc.object();
    }

    QJsonArray vectorArray(const QString &fileName) const
    {
        const QJsonObject doc = loadFixture(fileName);
        const QJsonArray arr = doc.value(QStringLiteral("vectors")).toArray();
        if (arr.isEmpty())
            qFatal("fixture %s has no vectors", qPrintable(fileName));
        return arr;
    }

    static bool indexForbidden(quint32 index)
    {
        const QByteArray be(reinterpret_cast<const char *>(&index), 4);
        return be.contains('\x0A') || be.contains('\x0D');
    }

    // Qt on little-endian hosts: build the big-endian encoding explicitly.
    static QByteArray beBytes(quint32 index)
    {
        QByteArray be;
        be.append(char((index >> 24) & 0xFF));
        be.append(char((index >> 16) & 0xFF));
        be.append(char((index >> 8) & 0xFF));
        be.append(char(index & 0xFF));
        return be;
    }

    static quint32 nextPermitted(quint32 candidate)
    {
        quint32 i = candidate;
        while (indexForbidden(i))
            ++i;
        return i;
    }

    static QByteArray hexToBytes(const QString &hex)
    {
        return QByteArray::fromHex(hex.toLatin1());
    }

private slots:
    void manifestSha256Sync()
    {
        const QJsonObject manifest = loadFixture(QStringLiteral("manifest.json"));
        QCOMPARE(manifest.value(QStringLiteral("standard_version")).toString(), QStringLiteral("1.2"));
        const QJsonObject files = manifest.value(QStringLiteral("files")).toObject();
        QCOMPARE(files.size(), 7);
        for (auto it = files.begin(); it != files.end(); ++it)
        {
            const QByteArray raw = readFixtureFile(it.key());
            const QString digest = QString::fromLatin1(
                QCryptographicHash::hash(raw, QCryptographicHash::Sha256).toHex());
            QCOMPARE(digest, it.value().toObject().value(QStringLiteral("sha256")).toString());
        }
    }

    void malformedRejectionShapes()
    {
        const QJsonArray vectors = vectorArray(QStringLiteral("malformed_inputs.json"));
        QCOMPARE(vectors.size(), 46);

        int authFailures = 0;
        int metadataFailures = 0;
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            const QString id = v.value(QStringLiteral("id")).toString();
            const QString error = v.value(QStringLiteral("expected_error")).toString();
            QVERIFY2(!error.isEmpty(), qPrintable(id + QStringLiteral(": expected_error")));
            const QString stage = v.value(QStringLiteral("expected_rejection_stage")).toString();
            QVERIFY2(stage == QStringLiteral("PROVIDER_FAILOVER") ||
                     stage == QStringLiteral("METADATA_VALIDATION"),
                     qPrintable(id + QStringLiteral(": unexpected rejection stage ") + stage));
            QCOMPARE(v.value(QStringLiteral("zero_output_required")).toBool(), true);
            if (error == QStringLiteral("AUTHENTICATION_FAILURE"))
            {
                ++authFailures;
                QCOMPARE(v.value(QStringLiteral("expected_rejection_stage")).toString(),
                         QStringLiteral("PROVIDER_FAILOVER"));
                QCOMPARE(v.value(QStringLiteral("provider_failover_permitted")).toBool(), true);
            }
            if (stage == QStringLiteral("METADATA_VALIDATION"))
            {
                ++metadataFailures;
                QCOMPARE(v.value(QStringLiteral("provider_failover_permitted")).toBool(), false);
            }
        }
        QCOMPARE(authFailures, 4);
        QCOMPARE(metadataFailures, 4);

        // header_syntax vectors carry a full =yencryption line to reject; the
        // invalid whitespace is the very thing they assert.
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            if (v.value(QStringLiteral("category")).toString() != QLatin1String("header_syntax"))
                continue;
            const QString id = v.value(QStringLiteral("id")).toString();
            const QString line = v.value(QStringLiteral("input_line")).toString();
            QVERIFY2(line.startsWith(QStringLiteral("=yencryption")) &&
                     line.length() > 12 &&
                     !line.at(12).isLetterOrNumber(),
                     qPrintable(id + QStringLiteral(": header_syntax vector missing input_line")));
        }

        // FORBIDDEN_SEGMENT_INDEX_BYTE vectors: bootstrap line is 22 bytes
        // with the segmentIndex in the 4 big-endian bytes at offset 16.
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            if (v.value(QStringLiteral("expected_error")).toString() !=
                QLatin1String("FORBIDDEN_SEGMENT_INDEX_BYTE"))
                continue;
            const QString id = v.value(QStringLiteral("id")).toString();
            const QByteArray line1 = hexToBytes(v.value(QStringLiteral("line1_hex")).toString());
            QCOMPARE(line1.size(), 22);
            const quint32 index = (quint32(quint8(line1.at(16))) << 24) |
                                  (quint32(quint8(line1.at(17))) << 16) |
                                  (quint32(quint8(line1.at(18))) << 8) |
                                  quint32(quint8(line1.at(19)));
            QVERIFY2(indexForbidden(index),
                     qPrintable(id + QStringLiteral(": index ") + QString::number(index) +
                                QStringLiteral(" should be forbidden")));
        }
    }

    void nzbMetaTagExpectations()
    {
        const QJsonArray vectors = vectorArray(QStringLiteral("nzb_segment_identity.json"));
        QCOMPARE(vectors.size(), 10);

        int encrypted = 0;
        int unencrypted = 0;
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            const QString id = v.value(QStringLiteral("id")).toString();
            const QString nzbXml = v.value(QStringLiteral("nzb_xml")).toString();
            if (v.value(QStringLiteral("is_encrypted")).toBool())
            {
                ++encrypted;
                QVERIFY2(nzbXml.contains(QStringLiteral("<meta type=\"yenc_encrypted\">true</meta>")),
                         qPrintable(id));
                QVERIFY2(nzbXml.contains(QStringLiteral("<meta type=\"password\">")), qPrintable(id));
            }
            else if (!v.value(QStringLiteral("is_encrypted")).toBool() &&
                     v.value(QStringLiteral("is_encrypted")) == QJsonValue(false))
            {
                ++unencrypted;
                QVERIFY2(!nzbXml.contains(QStringLiteral("<meta type=\"yenc_encrypted\">")), qPrintable(id));
                QVERIFY2(!nzbXml.contains(QStringLiteral("<meta type=\"password\">")), qPrintable(id));
                QCOMPARE(v.value(QStringLiteral("expected_valid")).toBool(), true);
            }
        }
        QVERIFY(encrypted > 0);
        QCOMPARE(unencrypted, 1);
    }

    void indexAllocationSkipRules()
    {
        const QJsonArray vectors = vectorArray(QStringLiteral("index_allocation.json"));
        QCOMPARE(vectors.size(), 4);
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            const QString id = v.value(QStringLiteral("id")).toString();
            const quint32 assigned = quint32(v.value(QStringLiteral("expected_assigned_index")).toInt());
            // By design (vector 04): candidate 269 is itself forbidden - the
            // uploader must never assign it - so only the assigned index is
            // required to be permitted.
            QVERIFY2(!indexForbidden(assigned), qPrintable(id + QStringLiteral(": assigned must be permitted")));
            const quint32 candidate = quint32(v.value(QStringLiteral("candidate_index")).toInt());
            QCOMPARE(nextPermitted(candidate), assigned);
            QCOMPARE(beBytes(assigned).toHex(), v.value(QStringLiteral("expected_index_hex")).toString());
        }

        // Canonical skip examples keep stable expected assignments.
        QHash<QString, quint32> byId;
        for (const QJsonValue &value : vectors)
        {
            const QJsonObject v = value.toObject();
            byId.insert(v.value(QStringLiteral("id")).toString(),
                        quint32(v.value(QStringLiteral("expected_assigned_index")).toInt()));
        }
        QCOMPARE(byId.value(QStringLiteral("index-allocation-01-skip-10")), quint32(11));
        QCOMPARE(byId.value(QStringLiteral("index-allocation-02-skip-13")), quint32(14));
        QCOMPARE(byId.value(QStringLiteral("index-allocation-03-skip-266")), quint32(267));
        QCOMPARE(byId.value(QStringLiteral("index-allocation-04-skip-269")), quint32(270));
    }
};

QTEST_MAIN(ConformanceVectorsTest)
#include "ConformanceVectors.moc"
